Monorepo corrections
Azure-Blade/Jet-Black pull request #2
Opened 2022-11-21 22:25 UTC by Fractal-Tess

2022-11-21 22:27 UTC, Fractal-Tess reviewed
* removed the shared tsconfigs as they were no longer used
* installed daisyui in tailwind package config for clearance and intellisense

2022-11-21 22:57 UTC, Layendan requested changes
Shouldn't we still keep the tsconfig since we're using typescript?
So keep the `base.json`, `package.json` but remove the `next.json` and `react-library.json` in the files array, and `README.md`.

2022-11-21 23:26 UTC, Fractal-Tess commented
So the issue here is that both of the projects that use typescript {tauri and the sveltekit} already have their *own* config that I haven't touched besides adding path aliases.

The thing with the tsconfig files is that they are only allowed to extend a single typescript file, {they cannot inherit multiple configs at the same time}

So given this knowledge, we know that the tsconfig file in the sveltekit project needs to inherit from the .svelte-kit generated folder.

That leaves only the tauri project. That one doesn't have a big config, so it doesn't make sense to split it up - in fact we should merge the node.tsconfig.json. All of that being said, we do not need a shared tsconfig like I originally thought.

Well... At least for now. Who knows how big this project might grow.

2022-11-22 00:54 UTC, Layendan approved these changes

2022-11-22 00:55 UTC, merged